// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication5_core.Models
{
    public partial class Book
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Column("price")]
        public double Price { get; set; }
        [Required]
        [Column("description")]
        public string Description { get; set; }
        [Required]
        [StringLength(50)]
        public string Categoryname { get; set; }
        [Column("scount")]
        public int Scount { get; set; }
        public int AuthorId { get; set; }
        [Column("imglink")]
        public string Imglink { get; set; }

        [ForeignKey(nameof(AuthorId))]
        [InverseProperty("Books")]
        public virtual Author Author { get; set; }
    }
}