// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication5_core.Models
{
    public partial class Category
    {
        public Category()
        {
            Books = new HashSet<Book>();
        }

        [Key]
        [StringLength(50)]
        public string Name { get; set; }
        public int Numofbooks { get; set; }

        [InverseProperty(nameof(Book.CategorynameNavigation))]
        public virtual ICollection<Book> Books { get; set; }
    }
}